### ISSUE TITLE
NVARCHAR support

### ISSUE THREAD

**Issue by ashokgkumar** [jpalomo/kafka-connect-mssqlserver-cdc#1]
Hi John, thanks for the connector.  It is pretty neat.  I did notice that it wasn't handling NVARCHAR sql datatype.  I have added it but wanted to let you know.  Thanks!

**Comment by jpalomo** [comment]
Thanks so much for checking it out!  I haven’t had time to work on this lately but I will definitely get that change in (I might even have it locally).  Please continue to provide any and all feedback. I hope to get this out to confluent by year end.   Cheers

**Comment by jpalomo** [comment]
This was an oversight on my part.   I have several other data types I need to revisit, but I went ahead pushed the change to add support for nvarchar along with updated integration tests.

[commit-6373d3f](https://github.com/jpalomo/kafka-connect-mssqlserver-cdc/commit/6373d3f3b219f2a2d6409f3ad8b9837acc736d07)

**Comment by ashokgkumar** [comment]
Thank you
